[package]
name = "ewb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ewb"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
regex = "1.11.1"
rustls = "0.23.25"
webpki-roots = "0.26.8"
